[package]
name = "zero2prod"
version = "0.1.0"
edition = "2024"

# We only can have 1 library in a package
[lib]
path = "src/lib.rs"

# We can have multiple binaries in a package
# [[xxx]] is TOML syntax for an array. [[bin]] means bin is an array
# Name is the binary output's name after we run cargo build
[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
axum = "0.8.9"
config = "0.15.25"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }

[dependencies.sqlx]
version = "0.9.0"
default-features = false
features = [
    "runtime-tokio",
    "tls-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
]

[dev-dependencies]
reqwest = "0.13.4" # only used in our integration tests
